name: Django CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: lucky@254ke
          MYSQL_DATABASE: test_db
          MYSQL_USER: Frank
          MYSQL_PASSWORD: lucky@254ke
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DATABASE_NAME: test_db
      DATABASE_USER: Frank
      DATABASE_PASSWORD: test@123
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            mysqladmin ping -h127.0.0.1 -udjango -pdjango123 && break
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Apply migrations
        run: |
          python manage.py migrate --noinput

      - name: Run tests
        run: |
          python manage.py test

      - name: Upload test results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: django-test-results
          path: reports/
