# Generated by Django 5.2.6 on 2025-09-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='conversation_id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='uuid',
        ),
    ]
